const en = {
  loginTitle: 'The Strength of Every Investor',
  SCORES: 'SCORES',
  login: 'Login',
  loginSubTitle: 'Please fill your detail to access your account.',
  id: 'Email or Mobile Number',
  password: 'Password',
  SignIn: 'Sign in',
  fPassword: 'Forgot Password',
  VCode: 'Verification code',
  OTPMessage: 'We have send  OTP code verification',
  success: 'Success',
  successDescriptions: 'OTP sent Successfully',
  signIn: 'Sign in',
  sec: 'Sec',
  submit: 'Submit',
  welcome: 'Welcome',
  ashish: 'Ashish Ranjan!',
  complainTitle: 'Complaint Details',
  total: 'Total',
  pending: 'Pending',
  resolve: 'Resolve',
  c1: 'Raise a Complaint',
  c2: 'View Complaint Status',
  c3: 'Seek Review',
  c4: 'Provide Feedback',
  c5: 'FAQ',
  c6: 'Entity Status',
  Logout:'Logout',
  home:'Home',
  aboutSEBI:'About SEBI',
  changePassword:'Change Password',
  FAQs:'FAQs',
  profileSetting:'Profile Setting',
  contactSEBI:'Contact SEBI',
  lastSuccessfulLogin:'Last Successful Login on',
  lastUnSuccessfulLogin:'Last Unsuccessful Login on',
  loginUse:'View Login Usage',
  confirmation:'Are you sure you want to logout?',
  cancel:'Cancel',
  ok:'Ok',
  changeLanguage:'Change Language',
  confirmationLanguageChange:'are you sure want to change language?',
  hindi:'Hindi',
  english:'English'
};

const hi = {
  loginTitle: 'हर निवेशक की ताकत',
  SCORES: 'स्कोर',
  login: 'लॉगिन',
  loginSubTitle: 'कृपया अपना खाता एक्सेस करने के लिए अपना विवरण भरें.',
  id: 'ईमेल या मोबाइल नंबर',
  password: 'पासवर्ड',
  SignIn: 'साइन इन करें',
  fPassword: 'पासवर्ड भूल गए',
  VCode: 'सत्यापन कोड',
  OTPMessage: 'हमने ओटीपी कोड सत्यापन भेजा है',
  success: 'सफलता',
  successDescriptions: 'OTP सफलतापूर्वक भेजा गया',
  signIn: 'साइन इन करें',
  sec: 'सेकंड ',
  submit: 'जमा करें',
  welcome: 'स्वागत है',
  ashish: 'आशीष रंजन!',
  complainTitle: 'शिकायत विवरण',
  total: 'कुल',
  pending: 'लंबित',
  resolve: 'कृतसंकल्‍प',
  c1: 'शिकायत दर्ज करें',
  c2: 'शिकायत की स्थिति देखें',
  c3: 'समीक्षा की तलाश करें',
  c4: 'प्रतिक्रिया दें',
  c5: 'एफएक्यू',
  c6: 'एंटिटी स्थिति',
  Logout:'लॉग आउट',
  home:'घर',
  aboutSEBI:'सेबी के बारे में',
  changePassword:'पासवर्ड बदलें',
  FAQs:'पूछे जाने वाले प्रश्न',
  profileSetting:'प्रोफ़ाइल सेटिंग',
  contactSEBI:'सेबी से संपर्क करें',
  lastSuccessfulLogin:'अंतिम सफल लॉगिन चालू',
  lastUnSuccessfulLogin:'अंतिम असफल लॉगिन चालू',
  loginUse:'लॉगिन उपयोग देखें',
  confirmation:'क्या आप लॉग आउट करना चाहते हैं?',
  cancel:'रद्द करना',
  ok:'ठीक है',
  changeLanguage:'भाषा बदलें',
  confirmationLanguageChange:'क्या आप वाकई भाषा बदलना चाहते हैं?',
  hindi:'हिंदी',
  english:'अंग्रेज़ी'
};

export default {en, hi};
